---
title: "heatmap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 22,
                      fig.height = 14)
```



```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(lubridate)
library(RColorBrewer)
library(dendextend)

data <- read_csv("MIL_for_R.csv")

clean_data <- data %>%
  clean_names() %>% 
  mutate(month = month(ymd(date_time), label = TRUE, abbr = FALSE)) %>% 
  mutate(date = date_time) %>% 
  mutate(julian_date = yday(date)) %>% 
  separate(date_time, into = c("y", "m", "d"), sep = "-") %>% 
  filter(y != 1994) %>% 
  mutate(inflow_af = inflow_cfs*1.9834591996927) %>% 
  mutate(outflow_af = outflow_csf*1.9834591996927) %>% 
  mutate(active_storage = storage_af-(520528-433800)) %>% 
  mutate(scenario_cfs = ifelse(active_storage > (433800*.9) & inflow_cfs > outflow_csf, active_storage - (433800*.9), NA)) %>% 
  mutate(scenario_af = scenario_cfs*1.9834591996927) %>% 
  mutate(binary = ifelse(scenario_af>0, 1, 0))
  




```


```{r}
heatmap <- ggplot(data = clean_data, aes(x = y, y = julian_date))+
  geom_tile(aes(fill = binary), show.legend = FALSE)+
  scale_fill_continuous(na.value = "none")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 50, hjust = 1, size = 36),
        axis.text.y = element_text(size = 36),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())+
  scale_x_discrete(labels = c(1995, "","","","", 
                              2000,"","","","", 
                              2005,"","","","", 
                              2010, "","","","", 
                              2015, "", "","","",
                              2020))+
  scale_y_continuous(expand = c(0,0),
                     labels = c("January", "February", "March",
                                "April", "May", "June", 
                                "July", "August", "September", 
                                "October", "November", "December"), 
                     breaks = c(15, 46, 74, 105, 135, 166, 196, 227, 258, 288, 319, 349))


heatmap

#should i add water year type to the x axis under year?
#do we like blue or is there another color scheme that would be better?
#anything else?


```




```{r, fig.width = 2, fig.height = 14}

binary_subset <- clean_data %>% 
  filter(binary == 1)


summary_plot <- ggplot(clean_data, aes(x = month, y = binary))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank())+
  scale_y_continuous(breaks = seq(0,150,50)) 

summary_plot


# attempt to make frequency graph of "criteria met" 

```











